travis:
  secure:
    BINSTAR_TOKEN: GlJDU8XELAMQqcJcun9vmoinrpB+tem+7qDDjvo5yNZGDsJC1ctcj8CDt4f8K4AYsfN3FJXjgA2KnOESx8Le+ZzmFbtiTgoOXWNjoV0+v0CDiK3yt9BwfQBjbjp572PTFAy/b5IsVBsBdYoBfRVR4oNvJT+1vVQfwXes37uBqAocrPl9nVGKlHSOLMtnm4Oqi/y3VgpX79oN9PpDqsGfECvlEjNz0PmU7p93wefDmRZd6UB2GzHCR0lqRS4mha1qIlnc5NQjxjHjBHGOb/HbPuWHKtWnLUKhRTDYTYKkL60RtHPv+d9pwyuem6MFp3CXPqSBe0rWvfI7z0ZX73R9tIv9vbyjVdwyF/5cgPqRAeucTOGTHiYpkl5qHAySpOUMTz83Vl3FrU/kAMQLGD50Q+SntVycmV3BsuQI4ya+GCipxLH6qIB+I0U2sD+rWP7vcrXsB8e2Aj04AsXudoAcHZGxBeBZ3SG8MMMawn2kg89/Hst5pBfnDBaN5A5UD3HBVUdsE5gXboBgkWbnrzi/rnHTGaV0EqiQhHjwqB+8jQN8zYnREteVW3x/9tsnIDxmRLw/vBvZzl62Fi62fbvAvjD0QQxd27B2M8H5IABx3UyLZuwk/WMXkJ6bQGQ69r2zr8c2o7y5F8j3Ll02H8inUghCkbts3vwZtmgr7SoIXew=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
